### PR TITLE
Parse Error and Image Processing

### PR DESCRIPTION
**Pull request by wzedi**
Hi,

Thanks for this code. I'm using it for a Business Catalyst website and it works well.

A couple of things emerged as I was using this. Initially I had a parse error. The feedback() function appears to be incorrectly referenced. I made the change to correct the parse error.

I also noticed that images were not being processed. The change at line 162 corrected that.

Cheers,
Warrick

### CODE REVIEW

**Comment by MattHealy** [comment]
The "images" tag in the XML format was deprecated some time ago and replaced with "objects", but it is good to support it for backwards compatibility, as some XML providers will still use it (realestate.com.au themselves still support it)

**Comment by wzedi** [comment]
Thanks Matt,

Apologies. I didn't see the deprecation note anywhere and the data I am working with does include the images tag. That's a little concerning so I'll be sure to check the source of my data.

**Comment by MattHealy** [comment]
Yes, it's an obscure reference buried deep within their DTD :-) you
definitely need to support it when importing data though.

**Comment by wzedi** [comment]
Not so deeply buried after all then. I do see it now.

I'll take solace in the fact that it's needed for backward compatibility as you say.

**Pull request merged**
